import { IndustryDemoConfig } from "../types";
import { CAFE_WORKFLOW_STEPS } from "./cafeConfig";

export const INDUSTRY_CONFIGS: Record<string, IndustryDemoConfig> = {
  cafe: {
    id: "cafe",
    name: "Mysore Artisan Roasters",
    tagline: "Single-origin pour-overs & fresh artisanal pastries",
    badgeText: "Artisan Roastery",
    primaryColor: "#D97706",
    accentColor: "#F59E0B",
    categories: ["Coffees", "Teas", "Bites", "Whole Beans"],
    workflowSteps: CAFE_WORKFLOW_STEPS,
  },
  restaurant: {
    id: "restaurant",
    name: "Royal Heritage Fine Dining",
    tagline: "Michelin-inspired tasting menus & courtyard reservations",
    badgeText: "Royal Fine Dining",
    primaryColor: "#E11D48",
    accentColor: "#F43F5E",
    categories: ["Starters", "Mains", "Desserts", "Cocktails"],
    workflowSteps: [
      { id: "menu", label: "1. Reserve", description: "Select date & table size" },
      { id: "coffee", label: "2. Courses", description: "Browse chef's tasting menu" },
      { id: "latte", label: "3. Selection", description: "Customize wine pairing" },
      { id: "cart", label: "4. Add", description: "Add items to reservation" },
      { id: "cart", label: "5. Review", description: "Check deposit & dietary notes" },
      { id: "checkout", label: "6. Pay Deposit", description: "Instant table confirmation" },
      { id: "confirmed", label: "7. Booked", description: "Table reserved calendar sync" },
    ],
  },
  dental: {
    id: "dental",
    name: "Apex Precision Dental Clinic",
    tagline: "Board-certified MDS specialists & 3D intraoral scans",
    badgeText: "Precision Dental",
    primaryColor: "#0284C7",
    accentColor: "#38BDF8",
    categories: ["Cleaning", "Whitening", "Orthodontics", "Implants"],
    workflowSteps: [
      { id: "menu", label: "1. Services", description: "Select dental treatment" },
      { id: "coffee", label: "2. Specialist", description: "Choose practitioner" },
      { id: "latte", label: "3. Slot", description: "Pick convenient time slot" },
      { id: "cart", label: "4. Details", description: "Input patient insurance info" },
      { id: "cart", label: "5. Summary", description: "Review procedure breakdown" },
      { id: "checkout", label: "6. Confirm", description: "Book appointment slot" },
      { id: "confirmed", label: "7. Scheduled", description: "Calendar invite & text sent" },
    ],
  },
  clinic: {
    id: "clinic",
    name: "CarePoint Multi-Specialty Clinic",
    tagline: "Senior doctor consultations & 24/7 emergency care",
    badgeText: "Multi-Specialty Clinic",
    primaryColor: "#0D9488",
    accentColor: "#2DD4BF",
    categories: ["General Care", "Cardiology", "Pediatrics", "Dermatology"],
    workflowSteps: [
      { id: "menu", label: "1. Triage", description: "Select health symptom/specialty" },
      { id: "coffee", label: "2. Doctor", description: "View verified doctor profiles" },
      { id: "latte", label: "3. Mode", description: "Select Video or In-person" },
      { id: "cart", label: "4. Records", description: "Attach symptom history" },
      { id: "cart", label: "5. Plan", description: "Review consultation fee" },
      { id: "checkout", label: "6. Pay", description: "Simple online payment" },
      { id: "confirmed", label: "7. Confirmed", description: "Telehealth link generated" },
    ],
  },
  gym: {
    id: "gym",
    name: "Pulse Athletic Club",
    tagline: "High-performance facility & CSCS master coaches",
    badgeText: "Athletic Club",
    primaryColor: "#8B5CF6",
    accentColor: "#A78BFA",
    categories: ["HIIT", "Strength", "Spin", "Yoga"],
    workflowSteps: [
      { id: "menu", label: "1. Schedule", description: "Browse class timetable" },
      { id: "coffee", label: "2. Class", description: "Select HIIT Power Hour" },
      { id: "latte", label: "3. Spot", description: "Pick mat/bike position" },
      { id: "cart", label: "4. Pass", description: "Select day pass or credit" },
      { id: "cart", label: "5. Locker", description: "Add locker & towel service" },
      { id: "checkout", label: "6. Checkout", description: "One-tap pass purchase" },
      { id: "confirmed", label: "7. Access Pass", description: "QR code check-in generated" },
    ],
  },
};
