import { TastingCourseItem } from "./types";

export const RESTAURANT_COURSES: TastingCourseItem[] = [
  {
    id: "rest-1",
    name: "Hokkaido Scallop Crudo",
    category: "starters",
    price: 24,
    description: "Pan-seared Hokkaido scallops with finger lime caviar, dashi emulsion, and shiso oil.",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop",
    winePairing: "2021 Dom. Leflaive Puligny-Montrachet",
    dietary: ["Gluten-Free"],
  },
  {
    id: "rest-2",
    name: "Black Truffle Burrata Tartine",
    category: "starters",
    price: 22,
    description: "Pugliese burrata, shaved Périgord black truffle, aged balsamic, micro basil on grilled sourdough.",
    image: "https://images.unsplash.com/photo-1541529086526-db283c563270?q=80&w=800&auto=format&fit=crop",
    winePairing: "2019 Vietti Roero Arneis",
    dietary: ["Vegetarian"],
  },
  {
    id: "rest-3",
    name: "Dry-Aged Wagyu Ribeye A5",
    category: "mains",
    price: 68,
    description: "45-day dry-aged Miyazaki A5 Wagyu, smoked bone marrow jus, roasted baby carrots, and pomme purée.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop",
    winePairing: "2018 Château Pontet-Canet Pauillac",
  },
  {
    id: "rest-4",
    name: "Wild Chilean Sea Bass",
    category: "mains",
    price: 48,
    description: "Miso-glazed sea bass, lemongrass beurre blanc, baby bok choy, and ginger infused broth.",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=800&auto=format&fit=crop",
    winePairing: "2020 Louis Jadot Meursault",
    dietary: ["Gluten-Free"],
  },
  {
    id: "rest-5",
    name: "Valrhona Dark Chocolate Soufflé",
    category: "desserts",
    price: 18,
    description: "70% Guanaja dark chocolate soufflé served warm with Madagascar bourbon vanilla bean gelato.",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=800&auto=format&fit=crop",
    winePairing: "2015 Taylor Fladgate 20 Yr Tawny Port",
    dietary: ["Vegetarian"],
  },
  {
    id: "rest-6",
    name: "Smoked Rosemary Old Fashioned",
    category: "cocktails",
    price: 20,
    description: "Single barrel bourbon, house smoked rosemary syrup, Angostura bitters, flamed orange peel.",
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop",
  },
];
