import { CafeProduct } from "./types";

export const CAFE_PRODUCTS: CafeProduct[] = [
  {
    id: "cafe-1",
    name: "Ethiopian Yirgacheffe Single-Origin",
    category: "coffees",
    price: 4.80,
    description: "Floral aromas with delicate jasmine notes, bergamot citrus, and a silky smooth body.",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop",
    badge: "Staff Pick",
    notes: "Notes: Jasmine, Bergamot, Peach",
    calories: 5,
  },
  {
    id: "cafe-2",
    name: "Artisan Flat White",
    category: "coffees",
    price: 4.50,
    description: "Double ristretto shot poured with velvety micro-foam oat milk for rich, balanced flavor.",
    image: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?q=80&w=800&auto=format&fit=crop",
    badge: "Popular",
    notes: "Notes: Milk Chocolate, Honey, Caramel",
    calories: 140,
  },
  {
    id: "cafe-3",
    name: "Kyoto Style Cold Brew",
    category: "coffees",
    price: 5.20,
    description: "Slow dripped over 12 hours using Japanese towers. Exceptionally smooth with zero bitterness.",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop",
    badge: "Signature",
    notes: "Notes: Dark Cocoa, Blackberry, Molasses",
    calories: 10,
  },
  {
    id: "cafe-4",
    name: "Ceremonial Uji Matcha Latte",
    category: "teas",
    price: 5.80,
    description: "First-harvest ceremonial grade green tea whisked traditionally with creamy steamed milk.",
    image: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?q=80&w=800&auto=format&fit=crop",
    badge: "Organic",
    notes: "Notes: Umami, Sweet Grass, Roasted Rice",
    calories: 110,
  },
  {
    id: "cafe-5",
    name: "Wild Bergamot Earl Grey Reserve",
    category: "teas",
    price: 4.20,
    description: "Full leaf organic black tea infused with natural Calabrian bergamot essential oils.",
    image: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=800&auto=format&fit=crop",
    notes: "Notes: Citrus, Malt, Wild Flower",
    calories: 2,
  },
  {
    id: "cafe-6",
    name: "Valrhona Chocolate Almond Croissant",
    category: "bites",
    price: 5.50,
    description: "Hand-laminated butter croissant stuffed with Belgian Valrhona dark chocolate and toasted almond frangipane.",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=800&auto=format&fit=crop",
    badge: "Fresh Baked",
    notes: "Contains Nuts & Dairy",
    calories: 380,
  },
  {
    id: "cafe-7",
    name: "Avocado & Poached Egg Sourdough",
    category: "bites",
    price: 9.50,
    description: "Smashed Hass avocado, organic poached egg, Aleppo chili flakes, microgreens on country sourdough.",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800&auto=format&fit=crop",
    badge: "Chef Special",
    notes: "Vegetarian",
    calories: 420,
  },
  {
    id: "cafe-8",
    name: "Mysore Espresso Blend (250g Whole Bean)",
    category: "beans",
    price: 18.00,
    description: "House roasted blend of Colombia Huila and Ethiopia Guji. Perfect balance of stonefruit and cacao.",
    image: "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?q=80&w=800&auto=format&fit=crop",
    badge: "House Roast",
    notes: "Medium Roast",
  },
];
