import { CafeProduct, CafeStaff, CafeReview } from "./types";

export const CAFE_PRODUCTS: CafeProduct[] = [
  {
    id: "cafe-1",
    name: "Chikmagalur Estate Single-Origin Pourover",
    category: "coffees",
    price: 280,
    description: "Hand-picked Arabica from high-altitude Western Ghats estates. Precision V60 extraction featuring dark chocolate, green cardamom & sweet plum.",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop",
    badge: "Master Roast",
    notes: "Notes: Dark Cocoa, Cardamom, Plum",
    calories: 5,
  },
  {
    id: "cafe-2",
    name: "Artisan Velvet Flat White",
    category: "coffees",
    price: 240,
    description: "Double ristretto shot of Chikmagalur espresso with silk micro-foamed A2 organic whole milk.",
    image: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?q=80&w=800&auto=format&fit=crop",
    badge: "Most Popular",
    notes: "Notes: Milk Chocolate, Honey, Nutmeg",
    calories: 140,
  },
  {
    id: "cafe-3",
    name: "Monsooned Malabar Nitro Cold Brew",
    category: "coffees",
    price: 260,
    description: "18-hour slow-steeped monsooned AA beans infused with nitrogen cascade. Creamy texture with spicy, low-acid finish.",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop",
    badge: "Signature Brew",
    notes: "Notes: Earthy Clove, Dark Cocoa, Roasted Hazelnut",
    calories: 10,
  },
  {
    id: "cafe-4",
    name: "Nilgiri Ceremonial Matcha Latte",
    category: "teas",
    price: 290,
    description: "Shade-grown organic green tea leaves from Nilgiri micro-farms whisked with velvety steamed oat milk.",
    image: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?q=80&w=800&auto=format&fit=crop",
    badge: "Organic Certified",
    notes: "Notes: Fresh Grass, Umami, Sweet Cream",
    calories: 110,
  },
  {
    id: "cafe-5",
    name: "Kulhad Masala Chai Reserve",
    category: "teas",
    price: 180,
    description: "Slow-simmered Assam orthodox black tea infused with crushed fresh ginger, green cardamom, and Kerala cinnamon served in terracotta.",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=800&auto=format&fit=crop",
    notes: "Notes: Crushed Ginger, Cardamom, Malt",
    calories: 85,
  },
  {
    id: "cafe-6",
    name: "Dark Chocolate & Pistachio Croissant",
    category: "bites",
    price: 220,
    description: "Hand-laminated French butter croissant filled with 70% dark Valrhona ganache and slow-roasted Kerala pistachios.",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=800&auto=format&fit=crop",
    badge: "Fresh Daily",
    notes: "Contains Nuts & Dairy",
    calories: 380,
  },
  {
    id: "cafe-7",
    name: "Parsi Style Akuri Sourdough Toast",
    category: "bites",
    price: 320,
    description: "Spiced soft scrambled organic eggs with fresh coriander, green chilies & caramelized onions on wild-yeast sourdough.",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800&auto=format&fit=crop",
    badge: "Chef Special",
    notes: "High Protein",
    calories: 420,
  },
  {
    id: "cafe-8",
    name: "Mysore Heritage Espresso (250g Bag)",
    category: "beans",
    price: 650,
    description: "In-house drum roasted blend of Chikmagalur Arabica (80%) and Coorg Robusta (20%). Full-bodied roast with dark cacao and organic jaggery notes.",
    image: "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?q=80&w=800&auto=format&fit=crop",
    badge: "House Roast",
    notes: "Medium-Dark Roast",
  },
];

export const CAFE_STAFF: CafeStaff[] = [
  {
    id: "staff-1",
    name: "Ramesh Gowda",
    role: "Head Coffee Roaster & Q Grader",
    experience: "12+ Years Roasting Experience",
    bio: "Certified Arabica Q Grader who sources single-origin lots directly from shade-grown estates across Chikmagalur and Coorg.",
    favoriteBrew: "Monsooned Malabar Cold Brew",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "staff-2",
    name: "Ananya Roy",
    role: "Lead Barista & Pour-Over Specialist",
    experience: "National Barista Finalist 2024",
    bio: "Passionate about extraction science and micro-foam texture, crafting sensory pour-over experiences for espresso connoisseurs.",
    favoriteBrew: "Chikmagalur Single-Origin V60",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "staff-3",
    name: "Chef Pierre Lecomte",
    role: "Executive Pastry Chef",
    experience: "Le Cordon Bleu Paris Alum",
    bio: "Combines classical French patisserie lamination with authentic Indian coastal spices and dry fruit pairings.",
    favoriteBrew: "Dark Chocolate & Pistachio Croissant",
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?q=80&w=800&auto=format&fit=crop",
  },
];

export const CAFE_REVIEWS: CafeReview[] = [
  {
    id: "rev-1",
    author: "Dr. Vikram Sethi",
    rating: 5,
    date: "2 days ago",
    comment: "The Monsooned Malabar Cold Brew is unmatched in the city. Subtle spice notes, velvety smooth, and the vibe at the roastery is world-class.",
    favoriteItem: "Monsooned Malabar Nitro Cold Brew",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "rev-2",
    author: "Meera Krishnan",
    rating: 5,
    date: "1 week ago",
    comment: "Hands down the best flat white and sourdough akuri toast in Gokulam. Staff are warm and extremely knowledgeable about bean origins.",
    favoriteItem: "Artisan Velvet Flat White",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "rev-3",
    author: "Karan Malhotra",
    rating: 5,
    date: "2 weeks ago",
    comment: "Bought the 250g Mysore Heritage whole beans for my espresso machine at home. Fresh roast date right on the valve bag. 10/10 quality.",
    favoriteItem: "Mysore Heritage Espresso Beans",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop",
  },
];

export const CAFE_HOURS = {
  weekdays: "7:00 AM – 10:30 PM",
  weekends: "7:00 AM – 11:00 PM",
  kitchenCloses: "10:00 PM Daily",
  cuppingSessions: "Saturdays 11:00 AM (Free Public Cupping)",
  address: "142 Gokulam Main Road, 3rd Stage, Mysuru, KA 570002",
  phone: "+91 821 245 8890",
};
